# Generated by Django 5.1.5 on 2025-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
